import type { Course, Semester, FutureTopic, PopularTopic } from './types';

export const COURSES: Course[] = [
  // ── Semester 1 ──
  { id:'BCS11',code:'BCS11',emoji:'🖥️',title:'Computer Basics and PC Software',desc:'Introduction to computers, hardware components, operating systems, MS Office tools, and essential PC software.',sem:['sem1'],badge:'blue',isLab:false,tags:['Hardware','OS','MS Office','PC Basics'],topics:['Introduction to Computers','Hardware Components','Operating System Basics','MS Word','MS Excel','MS PowerPoint','Internet Basics','Computer Security','File Management','Peripheral Devices'],lessons:12,progress:0},
  { id:'BCS12',code:'BCS12',emoji:'📐',title:'Mathematics',desc:'Foundation mathematics for BCA including sets, relations, functions, matrices, determinants, and basic calculus.',sem:['sem1'],badge:'red',isLab:false,tags:['Sets','Matrices','Functions','Calculus'],topics:['Set Theory','Relations & Functions','Matrices & Determinants','Differential Calculus','Integral Calculus','Probability Basics','Statistics','Permutations & Combinations','Number Theory','Boolean Algebra'],lessons:16,progress:0},
  { id:'BCSL13',code:'BCSL13',emoji:'🔬',title:'Computer Basics and PC Software Lab',desc:'Hands-on lab practice covering MS Office applications, basic computer operations, and PC software skills.',sem:['sem1'],badge:'green',isLab:true,tags:['Lab','MS Office','Practical','PC Skills'],topics:['MS Word Exercises','Excel Formulas Lab','PowerPoint Presentations','Internet Browsing','Email Handling','File & Folder Management','Windows OS Lab','Antivirus Practical','Typing Practice','Data Backup'],lessons:10,progress:0},
  { id:'ECO1',code:'ECO1',emoji:'🏢',title:'Business Organization',desc:'Fundamentals of business organizations, types of businesses, management principles, and organizational structures.',sem:['sem1'],badge:'gold',isLab:false,tags:['Business','Management','Organization','Commerce'],topics:['Forms of Business','Sole Proprietorship','Partnership','Companies','Management Functions','Marketing Basics','Finance Basics','HR Management','Business Ethics','Trade & Commerce'],lessons:10,progress:0},
  { id:'FEG2',code:'FEG2',emoji:'📝',title:'Foundation Course in English 2',desc:'Strengthening English language skills for technical and professional communication through reading, writing, and grammar.',sem:['sem1'],badge:'blue',isLab:false,tags:['English','Communication','Writing','Grammar'],topics:['Reading Comprehension','Grammar Review','Technical Writing','Letter Writing','Report Writing','Vocabulary Building','Listening Skills','Presentation Skills','Paragraph Writing','Précis Writing'],lessons:10,progress:0},
  // ── Semester 2 ──
  { id:'MCS11',code:'MCS11',emoji:'💡',title:'Problem Solving and Programming',desc:'Introduction to algorithmic thinking, flowcharts, pseudocode, and C programming fundamentals.',sem:['sem2'],badge:'blue',isLab:false,tags:['C Language','Algorithms','Flowcharts','Problem Solving'],topics:['Introduction to Algorithms','Flowcharts & Pseudocode','Variables & Data Types','Control Statements','Loops','Functions & Recursion','Arrays & Strings','Pointers','Structures','File Handling'],lessons:18,progress:0},
  { id:'MCS12',code:'MCS12',emoji:'⚙️',title:'Computer Organization and Assembly Language Programming',desc:'Computer architecture fundamentals, CPU design, memory organization, and 8086 assembly language programming.',sem:['sem2'],badge:'gold',isLab:false,tags:['Assembly','CPU','Memory','Architecture'],topics:['Basic Computer Organization','CPU Architecture','Memory Types','I/O Systems','Instruction Set','8086 Architecture','Assembly Syntax','Addressing Modes','Interrupts','Assembly Programs'],lessons:16,progress:0},
  { id:'MCS13',code:'MCS13',emoji:'🔢',title:'Discrete Mathematics',desc:'Mathematical foundations for computer science: logic, set theory, graph theory, combinatorics, and algebraic structures.',sem:['sem2'],badge:'red',isLab:false,tags:['Logic','Graph Theory','Sets','Combinatorics'],topics:['Propositional Logic','Predicate Logic','Set Theory','Relations','Functions','Graph Theory','Trees','Combinatorics','Algebraic Structures','Boolean Algebra'],lessons:18,progress:0},
  { id:'MCS15',code:'MCS15',emoji:'🗣️',title:'Communication Skills',desc:'Professional and technical communication skills including verbal, written communication, and presentations.',sem:['sem2'],badge:'green',isLab:false,tags:['Communication','Presentation','Writing','Soft Skills'],topics:['Communication Process','Verbal Communication','Non-Verbal Communication','Business Writing','Report Writing','Interview Skills','Group Discussion','Presentation Techniques','Email Etiquette','Technical Documentation'],lessons:10,progress:0},
  { id:'ECO2',code:'ECO2',emoji:'📊',title:'Accountancy – 1',desc:'Basic accounting principles, bookkeeping, journal entries, ledger accounts, trial balance, and financial statements.',sem:['sem2'],badge:'gold',isLab:false,tags:['Accounting','Journal','Ledger','Finance'],topics:['Accounting Basics','Double Entry System','Journal Entries','Ledger Posting','Trial Balance','Bank Reconciliation','Final Accounts','Depreciation','Errors & Rectification','Partnership Accounts'],lessons:12,progress:0},
  { id:'BCSL21',code:'BCSL21',emoji:'🔬',title:'C Language Programming Lab',desc:'Practical lab on C programming covering all key concepts through exercises and mini-projects.',sem:['sem2'],badge:'green',isLab:true,tags:['C Lab','Practical','Programming','Exercises'],topics:['Basic I/O Programs','Conditional Programs','Loop Programs','Function Programs','Array Programs','String Programs','Pointer Programs','Structure Programs','File Programs','Mini Project'],lessons:12,progress:0},
  { id:'BCSL22',code:'BCSL22',emoji:'🔬',title:'Assembly Language Programming Lab',desc:'Lab exercises in 8086 assembly language programming covering data movement, arithmetic, logic, and I/O operations.',sem:['sem2'],badge:'blue',isLab:true,tags:['Assembly Lab','8086','Practical','Low-Level'],topics:['8086 Setup','Data Transfer Instructions','Arithmetic Instructions','Logical Instructions','Loop Instructions','String Instructions','I/O Programming','Interrupt Handling','Memory Operations','Assembly Projects'],lessons:10,progress:0},
  // ── Semester 3 ──
  { id:'MCS14',code:'MCS14',emoji:'📋',title:'System Analysis and Design',desc:'SDLC models, requirements engineering, system design techniques, DFD, ER diagrams, and project documentation.',sem:['sem3'],badge:'gold',isLab:false,tags:['SDLC','DFD','System Design','Analysis'],topics:['System Development Life Cycle','Feasibility Study','Requirements Analysis','DFD & Data Dictionary','ER Diagram','Structured Design','Prototyping','Testing Strategies','Implementation & Maintenance','Project Management'],lessons:14,progress:0},
  { id:'MCS21',code:'MCS21',emoji:'🌳',title:'Data and File Structures',desc:'Fundamental data structures including arrays, linked lists, stacks, queues, trees, graphs, and file organization.',sem:['sem3'],badge:'blue',isLab:false,tags:['Linked Lists','Trees','Graphs','Sorting'],topics:['Arrays & 2D Arrays','Linked Lists (Single/Double)','Stacks & Applications','Queues & Deques','Binary Trees','Binary Search Tree','Heap & Priority Queue','Graph Algorithms','Sorting Algorithms','File Organization Methods'],lessons:22,progress:0},
  { id:'MCS23',code:'MCS23',emoji:'🗄️',title:'Introduction to Database Management Systems',desc:'DBMS concepts, relational model, SQL, normalization, transaction management, and database design principles.',sem:['sem3'],badge:'red',isLab:false,tags:['SQL','Normalization','DBMS','ER Model'],topics:['Introduction to DBMS','ER Model & Mapping','Relational Model','SQL DDL & DML','Joins & Subqueries','Normalization (1NF–BCNF)','Transactions & ACID','Concurrency Control','Database Security','Query Optimization'],lessons:20,progress:0},
  { id:'BCS31',code:'BCS31',emoji:'💻',title:'Programming in C++',desc:'Object-oriented programming with C++ – classes, inheritance, polymorphism, templates, exception handling, and STL.',sem:['sem3'],badge:'green',isLab:false,tags:['C++','OOP','Classes','Inheritance'],topics:['C++ Introduction','Classes & Objects','Constructors & Destructors','Inheritance','Polymorphism & Virtual Functions','Operator Overloading','Templates','Exception Handling','STL Overview','File I/O in C++'],lessons:20,progress:0},
  { id:'BCSL32',code:'BCSL32',emoji:'🔬',title:'C++ Programming Lab',desc:'Practical C++ lab covering OOP implementation, file handling, STL usage, and class-based mini projects.',sem:['sem3'],badge:'blue',isLab:true,tags:['C++ Lab','OOP Practical','STL','Exercises'],topics:['Basic Class Programs','Inheritance Programs','Polymorphism Programs','Operator Overloading Lab','Template Programs','Exception Handling Lab','STL Programs','File I/O Lab','Mini Project 1','Mini Project 2'],lessons:12,progress:0},
  { id:'BCSL33',code:'BCSL33',emoji:'🔬',title:'Data and File Structures Lab',desc:'Implementation lab for all major data structures and file handling – using C or C++.',sem:['sem3'],badge:'gold',isLab:true,tags:['DSA Lab','Practical','Linked List','Tree'],topics:['Array Operations','Linked List Programs','Stack Implementation','Queue Programs','BST Programs','Heap Programs','Graph BFS/DFS','Sorting Implementations','File Structure Programs','Mini Project'],lessons:12,progress:0},
  { id:'BCSL34',code:'BCSL34',emoji:'🔬',title:'DBMS Lab',desc:'SQL practical lab covering DDL, DML, joins, normalization exercises, triggers, and stored procedures.',sem:['sem3'],badge:'red',isLab:true,tags:['SQL Lab','DBMS Practical','Queries','PL/SQL'],topics:['CREATE/ALTER/DROP','INSERT/UPDATE/DELETE','SELECT & WHERE','JOIN Operations','Subqueries','GROUP BY & HAVING','Views & Indexes','Triggers','Stored Procedures','Mini DB Project'],lessons:12,progress:0},
  // ── Semester 4 ──
  { id:'MCSL16',code:'MCSL16',emoji:'🌐',title:'Internet Concepts and Web Design',desc:'Internet fundamentals, HTML5, CSS3, JavaScript basics, responsive design, and web hosting concepts.',sem:['sem4'],badge:'green',isLab:false,tags:['HTML','CSS','JavaScript','Web Design'],topics:['Internet & WWW Basics','HTML5 Structure','CSS3 Styling','CSS Flexbox & Grid','JavaScript Fundamentals','DOM Manipulation','Forms & Validation','Responsive Design','Web Hosting','Browser DevTools'],lessons:18,progress:0},
  { id:'MCS24',code:'MCS24',emoji:'☕',title:'Object Oriented Techniques and Java Programming',desc:'Java programming covering OOP concepts, exception handling, collections, multi-threading, and Java I/O streams.',sem:['sem4'],badge:'gold',isLab:false,tags:['Java','OOP','Threads','Collections'],topics:['Java Basics & JVM','Classes & Objects','Inheritance in Java','Interfaces & Abstract Classes','Exception Handling','Collections Framework','Generics','Multi-threading','Java I/O Streams','JDBC Intro'],lessons:22,progress:0},
  { id:'BCS40',code:'BCS40',emoji:'📈',title:'Statistical Techniques',desc:'Statistical methods for data analysis – probability distributions, hypothesis testing, regression, correlation, and ANOVA.',sem:['sem4'],badge:'blue',isLab:false,tags:['Statistics','Probability','Regression','ANOVA'],topics:['Descriptive Statistics','Probability Theory','Probability Distributions','Sampling Techniques','Hypothesis Testing','Chi-Square Test','t-Test & F-Test','Regression Analysis','Correlation','ANOVA'],lessons:16,progress:0},
  { id:'BCS41',code:'BCS41',emoji:'🔗',title:'Fundamentals of Computer Networks',desc:'Network topologies, OSI and TCP/IP models, IP addressing, routing, network protocols, and security basics.',sem:['sem4'],badge:'red',isLab:false,tags:['OSI Model','TCP/IP','Routing','Protocols'],topics:['Network Fundamentals','Network Topologies','OSI Reference Model','TCP/IP Model','IP Addressing & Subnetting','Routing Protocols','Transport Layer','Application Layer Protocols','Network Security','Wireless Networks'],lessons:20,progress:0},
  { id:'BCS42',code:'BCS42',emoji:'🧮',title:'Introduction to Algorithm Design',desc:'Algorithm analysis, design paradigms – divide & conquer, dynamic programming, greedy approach, and NP-completeness.',sem:['sem4'],badge:'blue',isLab:false,tags:['Algorithms','Complexity','DP','Greedy'],topics:['Algorithm Analysis & Big-O','Divide & Conquer','Sorting: Merge/Quick Sort','Dynamic Programming','Greedy Algorithms','Graph Algorithms','Backtracking','Branch & Bound','NP Completeness','Approximation Algorithms'],lessons:18,progress:0},
  { id:'BCSL43',code:'BCSL43',emoji:'🔬',title:'Java Programming Lab',desc:'Java practical lab – applets, Swing GUI, file I/O, JDBC, and multithreading through hands-on exercises.',sem:['sem4'],badge:'green',isLab:true,tags:['Java Lab','Swing','JDBC','Practical'],topics:['Basic Java Programs','OOP Programs','Exception Programs','Collections Lab','Multithreading Lab','File I/O Lab','Swing GUI Lab','JDBC Programs','Applet Programs','Mini Java Project'],lessons:12,progress:0},
  { id:'BCSL44',code:'BCSL44',emoji:'🔬',title:'Statistical Techniques Lab',desc:'Statistical lab using software tools to perform data analysis, plotting graphs, and hypothesis testing.',sem:['sem4'],badge:'gold',isLab:true,tags:['Statistics Lab','Data Analysis','Graphs','Practical'],topics:['Descriptive Stats Lab','Probability Lab','Normal Distribution Lab','Hypothesis Testing Lab','Chi-Square Lab','t-Test Lab','Regression Lab','Correlation Lab','ANOVA Lab','Statistical Report'],lessons:10,progress:0},
  { id:'BCSL45',code:'BCSL45',emoji:'🔬',title:'Algorithms Design Lab',desc:'Lab implementation of classical algorithms – sorting, searching, graph algorithms, dynamic programming, and analysis.',sem:['sem4'],badge:'red',isLab:true,tags:['Algorithms Lab','Sorting','Graph','DP Practical'],topics:['Sorting Algorithm Lab','Binary Search Lab','Divide & Conquer Lab','Dynamic Programming Lab','Greedy Algorithm Lab','Graph BFS/DFS Lab','Shortest Path Lab','Backtracking Lab','Complexity Analysis','Final Project'],lessons:12,progress:0},
];

export const SEMESTERS: Semester[] = [
  { num:1, color:'#6366f1', bg:'rgba(99,102,241,.15)', label:'Year 1 • Sem 1', subjects:['BCS11','BCS12','BCSL13','ECO1','FEG2'] },
  { num:2, color:'#10b981', bg:'rgba(16,185,129,.15)', label:'Year 1 • Sem 2', subjects:['MCS11','MCS12','MCS13','MCS15','ECO2','BCSL21','BCSL22'] },
  { num:3, color:'#f59e0b', bg:'rgba(245,158,11,.15)', label:'Year 2 • Sem 3', subjects:['MCS14','MCS21','MCS23','BCS31','BCSL32','BCSL33','BCSL34'] },
  { num:4, color:'#ef4444', bg:'rgba(239,68,68,.15)',  label:'Year 2 • Sem 4', subjects:['MCSL16','MCS24','BCS40','BCS41','BCS42','BCSL43','BCSL44','BCSL45'] },
];

export const FUTURE_TOPICS: FutureTopic[] = [
  { id:'frontend',emoji:'🎨',title:'Frontend Development',desc:'Build beautiful, interactive UIs using HTML5, CSS3, JavaScript, React, and modern frontend tooling.',badge:'green',color:'#10b981',tags:['HTML','CSS','React','JavaScript'],topics:['HTML5 Semantics','CSS3 & Animations','Flexbox & Grid','JavaScript ES6+','DOM & Events','React Basics','React Hooks','State Management','TypeScript Intro','Responsive Design','Performance Optimization','Accessibility (a11y)'],lessons:28,progress:0},
  { id:'backend',emoji:'⚙️',title:'Backend Development',desc:'Build robust server-side applications and REST APIs using Node.js, Express, Python, and Java frameworks.',badge:'blue',color:'#6366f1',tags:['Node.js','REST API','Express','Python'],topics:['HTTP & Request/Response','REST API Design','Node.js Basics','Express Framework','Middleware','Authentication & JWT','Sessions & Cookies','File Upload','Error Handling','API Security','Rate Limiting','MVC Pattern'],lessons:24,progress:0},
  { id:'database',emoji:'🗄️',title:'Database (SQL & NoSQL)',desc:'Master relational databases with PostgreSQL, MySQL and non-relational databases like MongoDB and Redis.',badge:'gold',color:'#f59e0b',tags:['PostgreSQL','MongoDB','SQL','Redis'],topics:['SQL Deep Dive','PostgreSQL Setup','MySQL Basics','Joins & Aggregations','Indexes & Performance','Stored Procedures','Transactions','MongoDB CRUD','Mongoose ODM','Redis Caching','Database Design','ORM / Prisma'],lessons:22,progress:0},
  { id:'git-github',emoji:'🐙',title:'Git & GitHub',desc:'Master version control with Git – branching strategies, pull requests, collaboration, and GitHub workflows.',badge:'red',color:'#ef4444',tags:['Git','GitHub','Branching','Pull Requests'],topics:['Git Init & Config','Staging & Commits','Branching Strategy','Merging & Rebasing','Resolving Conflicts','Remote Repositories','Pull Requests & Reviews','GitHub Actions Basics','Fork & Clone','Git Tags & Releases','.gitignore','Git Best Practices'],lessons:16,progress:0},
  { id:'deployment',emoji:'🚀',title:'Deployment',desc:'Deploy web applications to the cloud using Vercel, Netlify, Railway, AWS, and Docker containers.',badge:'blue',color:'#38bdf8',tags:['Vercel','Docker','AWS','Netlify'],topics:['Vercel Deployment','Netlify Deployment','Railway & Render','Environment Variables','Domain & DNS Setup','HTTPS & SSL','Docker Basics','Docker Compose','Nginx Basics','PM2 Process Manager','AWS EC2 Intro','Cloud Storage (S3)'],lessons:18,progress:0},
  { id:'cicd',emoji:'🔄',title:'Basic CI/CD',desc:'Automate testing and deployment pipelines using GitHub Actions, workflows, and continuous integration principles.',badge:'green',color:'#a78bfa',tags:['GitHub Actions','CI/CD','Automation','Testing'],topics:['CI/CD Concepts','GitHub Actions Setup','Workflow YAML Syntax','Automated Testing','Build Pipelines','Linting & Formatting','Code Coverage','Deployment Automation','Secrets Management','Matrix Builds','Caching in CI','Monitoring Deployments'],lessons:14,progress:0},
  { id:'system-design',emoji:'🏗️',title:'System Design',desc:'Learn to design scalable, reliable systems – architecture patterns, caching, load balancing, and microservices.',badge:'gold',color:'#f472b6',tags:['Architecture','Scalability','Caching','Microservices'],topics:['System Design Basics','Scalability Concepts','Load Balancing','Caching Strategies','Database Sharding','CAP Theorem','Microservices vs Monolith','Message Queues','API Gateway','CDN & Edge','Rate Limiting Design','Real-world Case Studies'],lessons:20,progress:0},
];

export const POPULAR_TOPICS: PopularTopic[] = [
  { icon:'🔗', text:'Linked Lists',       count:'12 lessons', id:'MCS21',         type:'bca' },
  { icon:'🗃️', text:'SQL Queries',        count:'10 lessons', id:'MCS23',         type:'bca' },
  { icon:'🌲', text:'Binary Trees',        count:'8 lessons',  id:'MCS21',         type:'bca' },
  { icon:'🔢', text:'Sorting Algorithms',  count:'9 lessons',  id:'BCS42',         type:'bca' },
  { icon:'🌍', text:'TCP/IP Protocol',     count:'6 lessons',  id:'BCS41',         type:'bca' },
  { icon:'🏛️', text:'Normalization',       count:'5 lessons',  id:'MCS23',         type:'bca' },
  { icon:'🔁', text:'Recursion',           count:'8 lessons',  id:'MCS11',         type:'bca' },
  { icon:'🎨', text:'React Basics',        count:'8 lessons',  id:'frontend',      type:'future' },
  { icon:'🐙', text:'Git Branching',       count:'6 lessons',  id:'git-github',    type:'future' },
  { icon:'🚀', text:'Vercel Deploy',       count:'5 lessons',  id:'deployment',    type:'future' },
  { icon:'🏗️', text:'System Architecture', count:'7 lessons',  id:'system-design', type:'future' },
  { icon:'🔄', text:'GitHub Actions',      count:'5 lessons',  id:'cicd',          type:'future' },
];
